// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/clusters": {
            "get": {
                "description": "Returns a list of clusters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clusters"
                ],
                "summary": "List clusters",
                "responses": {
                    "200": {
                        "description": "List of clusters",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ListClustersResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new cluster entity",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clusters"
                ],
                "summary": "Create a new cluster",
                "parameters": [
                    {
                        "description": "Create cluster request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.CreateClusterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Cluster created",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ClusterResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/clusters/{id}": {
            "get": {
                "description": "Retrieve a cluster by its id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clusters"
                ],
                "summary": "Get cluster by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cluster retrieved",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ClusterResponse"
                        }
                    },
                    "404": {
                        "description": "Cluster not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing cluster's fields",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clusters"
                ],
                "summary": "Update cluster",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update cluster request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.UpdateClusterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated cluster",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ClusterResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Cluster not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes the cluster and returns a confirmation message",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clusters"
                ],
                "summary": "Delete cluster",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Deletion confirmation",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.DeleteClusterResponse"
                        }
                    },
                    "404": {
                        "description": "Cluster not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/diagnosis/diagnose": {
            "post": {
                "description": "Run a diagnosis on the supplied cluster and get insights/recommendations",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "diagnosis"
                ],
                "summary": "Diagnose cluster",
                "parameters": [
                    {
                        "description": "Diagnose request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.DiagnoseClusterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Diagnosis result",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.DiagnoseClusterResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Rate limit exceeded",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/droplets": {
            "get": {
                "description": "Returns a list of droplets (optionally filtered by cluster)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "droplets"
                ],
                "summary": "List droplets",
                "responses": {
                    "200": {
                        "description": "List of droplets",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ListDropletsResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Provisions a new droplet. Provide region/size/image and optionally a cluster_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "droplets"
                ],
                "summary": "Create a new droplet",
                "parameters": [
                    {
                        "description": "Create droplet request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.CreateDropletRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Droplet created",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.DropletResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error while provisioning",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/droplets/{id}": {
            "get": {
                "description": "Returns a single droplet by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "droplets"
                ],
                "summary": "Get droplet by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Droplet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Droplet retrieved",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.DropletResponse"
                        }
                    },
                    "404": {
                        "description": "Droplet not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a droplet and returns a confirmation message",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "droplets"
                ],
                "summary": "Delete droplet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Droplet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Deletion confirmation",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.DeleteDropletResponse"
                        }
                    },
                    "404": {
                        "description": "Droplet not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health/{clusterId}": {
            "get": {
                "description": "Performs health checks on a cluster and returns the current health status and issues",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "monitoring"
                ],
                "summary": "Health check",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster ID",
                        "name": "clusterId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Health status",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.HealthCheckResponse"
                        }
                    },
                    "404": {
                        "description": "Cluster not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/hello": {
            "post": {
                "description": "Returns a greeting message for the supplied name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hello"
                ],
                "summary": "Say hello",
                "parameters": [
                    {
                        "description": "Hello request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.HelloRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Greeting created",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.HelloResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/jobs": {
            "get": {
                "description": "Returns paginated jobs list with sorting options",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "List jobs",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort column",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort direction (asc/desc)",
                        "name": "sort_dir",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of jobs",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ListJobsResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a background job (provision/diagnose/scale/monitor)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "Create job",
                "parameters": [
                    {
                        "description": "Create job request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.CreateJobRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Job created",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.JobResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Rate limit exceeded",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/jobs/{id}": {
            "get": {
                "description": "Retrieve job status/result by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "Get job by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Job retrieved",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.JobResponse"
                        }
                    },
                    "404": {
                        "description": "Job not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/metrics": {
            "get": {
                "description": "Return metrics filtered by cluster and/or type (paginated)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "monitoring"
                ],
                "summary": "Query metrics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster ID filter",
                        "name": "cluster_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Metric type (cpu/memory/disk/network)",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Metrics result",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.GetMetricsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/observability/ratelimit": {
            "get": {
                "description": "Get available tokens and configuration for a rate limiter (supports scope filters)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "observability"
                ],
                "summary": "Query rate limiter status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Limiter name (e.g. diagnosis or jobs_create)",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Optional scope type (global/user/cluster)",
                        "name": "scope_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Optional scope id for user/cluster",
                        "name": "scope_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Limiter status",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Missing/invalid input",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "No such limiter",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/observability/ratelimit/config": {
            "get": {
                "description": "Retrieve persisted limiter config for a name and optional scope",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "observability"
                ],
                "summary": "Get persisted limiter config",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Limiter name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Optional scope type",
                        "name": "scope_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Optional scope id",
                        "name": "scope_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Found config",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Missing name",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Store or update refill/capacity for a named limiter and scope",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "observability"
                ],
                "summary": "Persist limiter configuration",
                "parameters": [
                    {
                        "description": "Limiter config request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Config saved",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a stored limiter config by key or name+scope",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "observability"
                ],
                "summary": "Delete persisted limiter config",
                "parameters": [
                    {
                        "description": "Delete config request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Deletion result",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Missing input",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/observability/ratelimit/config/list": {
            "get": {
                "description": "Returns list of stored limiter configs filtered by name/scope",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "observability"
                ],
                "summary": "List persisted limiter configs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Optional limiter name filter",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Optional scope type",
                        "name": "scope_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Optional scope id",
                        "name": "scope_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of configs",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/observability/workerpool": {
            "get": {
                "description": "Snapshot of worker pool (counts, queue) for observability",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "observability"
                ],
                "summary": "Worker pool status",
                "responses": {
                    "200": {
                        "description": "Worker pool snapshot",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_AvinashMahala_ClusterGenie_backend_core-api_models.Cluster": {
            "type": "object",
            "properties": {
                "droplets": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string",
                    "example": "cluster-1"
                },
                "last_checked": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "example": "production-cluster"
                },
                "region": {
                    "type": "string",
                    "example": "nyc3"
                },
                "status": {
                    "description": "healthy, warning, critical",
                    "type": "string",
                    "example": "healthy"
                }
            }
        },
        "github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ClusterResponse": {
            "type": "object",
            "properties": {
                "cluster": {
                    "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.Cluster"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_AvinashMahala_ClusterGenie_backend_core-api_models.CreateClusterRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "region": {
                    "type": "string"
                }
            }
        },
        "github_com_AvinashMahala_ClusterGenie_backend_core-api_models.CreateDropletRequest": {
            "type": "object",
            "properties": {
                "cluster_id": {
                    "description": "Optional cluster ID to assign this droplet to",
                    "type": "string"
                },
                "image": {
                    "type": "string",
                    "example": "ubuntu-20-04-x64"
                },
                "name": {
                    "type": "string",
                    "example": "web-01"
                },
                "region": {
                    "type": "string",
                    "example": "nyc3"
                },
                "size": {
                    "type": "string",
                    "example": "s-1vcpu-1gb"
                }
            }
        },
        "github_com_AvinashMahala_ClusterGenie_backend_core-api_models.CreateJobRequest": {
            "type": "object",
            "properties": {
                "parameters": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_AvinashMahala_ClusterGenie_backend_core-api_models.DeleteClusterResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_AvinashMahala_ClusterGenie_backend_core-api_models.DeleteDropletResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_AvinashMahala_ClusterGenie_backend_core-api_models.DiagnoseClusterRequest": {
            "type": "object",
            "properties": {
                "cluster_id": {
                    "type": "string"
                }
            }
        },
        "github_com_AvinashMahala_ClusterGenie_backend_core-api_models.DiagnoseClusterResponse": {
            "type": "object",
            "properties": {
                "cluster": {
                    "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.Cluster"
                },
                "insights": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "recommendations": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_AvinashMahala_ClusterGenie_backend_core-api_models.Droplet": {
            "type": "object",
            "properties": {
                "cluster": {
                    "description": "Cluster object (optional) when returning droplet responses",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.Cluster"
                        }
                    ]
                },
                "cluster_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "image": {
                    "type": "string",
                    "example": "ubuntu-20-04-x64"
                },
                "ip_address": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "example": "web-01"
                },
                "region": {
                    "type": "string",
                    "example": "nyc3"
                },
                "size": {
                    "type": "string",
                    "example": "s-1vcpu-1gb"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "github_com_AvinashMahala_ClusterGenie_backend_core-api_models.DropletResponse": {
            "type": "object",
            "properties": {
                "droplet": {
                    "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.Droplet"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "The error message\nexample: Invalid request payload",
                    "type": "string"
                }
            }
        },
        "github_com_AvinashMahala_ClusterGenie_backend_core-api_models.GetMetricsResponse": {
            "type": "object",
            "properties": {
                "metrics": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.Metric"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "period": {
                    "type": "string"
                },
                "total_count": {
                    "type": "integer"
                }
            }
        },
        "github_com_AvinashMahala_ClusterGenie_backend_core-api_models.HealthCheckResponse": {
            "type": "object",
            "properties": {
                "cluster_id": {
                    "type": "string"
                },
                "issues": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "status": {
                    "description": "healthy, warning, critical",
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "github_com_AvinashMahala_ClusterGenie_backend_core-api_models.HelloRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "Ava"
                }
            }
        },
        "github_com_AvinashMahala_ClusterGenie_backend_core-api_models.HelloResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Hello, Ava from ClusterGenie!"
                }
            }
        },
        "github_com_AvinashMahala_ClusterGenie_backend_core-api_models.Job": {
            "type": "object",
            "properties": {
                "cluster_id": {
                    "type": "string",
                    "example": "cluster-1"
                },
                "completed_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "error": {
                    "type": "string",
                    "example": ""
                },
                "id": {
                    "type": "string",
                    "example": "job-1234"
                },
                "parameters": {
                    "description": "JSON string of parameters",
                    "type": "string"
                },
                "progress": {
                    "type": "integer"
                },
                "result": {
                    "type": "string",
                    "example": "OK"
                },
                "status": {
                    "description": "pending, running, completed, failed",
                    "type": "string",
                    "example": "pending"
                },
                "trace_id": {
                    "type": "string"
                },
                "type": {
                    "description": "provision, diagnose, scale, monitor",
                    "type": "string",
                    "example": "provision"
                }
            }
        },
        "github_com_AvinashMahala_ClusterGenie_backend_core-api_models.JobResponse": {
            "type": "object",
            "properties": {
                "job": {
                    "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.Job"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ListClustersResponse": {
            "type": "object",
            "properties": {
                "clusters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.Cluster"
                    }
                }
            }
        },
        "github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ListDropletsResponse": {
            "type": "object",
            "properties": {
                "droplets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.Droplet"
                    }
                }
            }
        },
        "github_com_AvinashMahala_ClusterGenie_backend_core-api_models.ListJobsResponse": {
            "type": "object",
            "properties": {
                "jobs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_AvinashMahala_ClusterGenie_backend_core-api_models.Job"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "github_com_AvinashMahala_ClusterGenie_backend_core-api_models.Metric": {
            "type": "object",
            "properties": {
                "cluster_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "type": {
                    "description": "cpu, memory, disk, network",
                    "type": "string"
                },
                "unit": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "github_com_AvinashMahala_ClusterGenie_backend_core-api_models.UpdateClusterRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "region": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "ClusterGenie API",
	Description:      "REST API for ClusterGenie - DigitalOcean droplet management and monitoring",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
