// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/hello": {
            "post": {
                "summary": "Say hello",
                "description": "Returns a greeting message",
                "tags": ["Hello"],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [{
                    "in": "body",
                    "name": "request",
                    "description": "Hello request",
                    "required": true,
                    "schema": {
                        "$ref": "#/definitions/models.HelloRequest"
                    }
                }],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.HelloResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/droplets": {
            "post": {
                "summary": "Create a new droplet",
                "description": "Creates a new DigitalOcean droplet",
                "tags": ["Provisioning"],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [{
                    "in": "body",
                    "name": "request",
                    "description": "Droplet creation request",
                    "required": true,
                    "schema": {
                        "$ref": "#/definitions/models.CreateDropletRequest"
                    }
                }],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.DropletResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "summary": "List all droplets",
                "description": "Returns a list of all droplets",
                "tags": ["Provisioning"],
                "produces": ["application/json"],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ListDropletsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/droplets/{id}": {
            "get": {
                "summary": "Get droplet by ID",
                "description": "Returns a specific droplet by its ID",
                "tags": ["Provisioning"],
                "produces": ["application/json"],
                "parameters": [{
                    "in": "path",
                    "name": "id",
                    "description": "Droplet ID",
                    "required": true,
                    "type": "string"
                }],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DropletResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "summary": "Delete droplet",
                "description": "Deletes a droplet by its ID",
                "tags": ["Provisioning"],
                "produces": ["application/json"],
                "parameters": [{
                    "in": "path",
                    "name": "id",
                    "description": "Droplet ID",
                    "required": true,
                    "type": "string"
                }],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DeleteDropletResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/diagnosis/diagnose": {
            "post": {
                "summary": "Diagnose cluster",
                "description": "Performs diagnostic analysis on a cluster",
                "tags": ["Diagnosis"],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [{
                    "in": "body",
                    "name": "request",
                    "description": "Cluster diagnosis request",
                    "required": true,
                    "schema": {
                        "$ref": "#/definitions/models.DiagnoseClusterRequest"
                    }
                }],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DiagnoseClusterResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/jobs": {
            "post": {
                "summary": "Create a new job",
                "description": "Creates a new job for cluster operations",
                "tags": ["Jobs"],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [{
                    "in": "body",
                    "name": "request",
                    "description": "Job creation request",
                    "required": true,
                    "schema": {
                        "$ref": "#/definitions/models.CreateJobRequest"
                    }
                }],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.JobResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "summary": "List all jobs",
                "description": "Returns a list of all jobs",
                "tags": ["Jobs"],
                "produces": ["application/json"],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ListJobsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/jobs/{id}": {
            "get": {
                "summary": "Get job by ID",
                "description": "Returns a specific job by its ID",
                "tags": ["Jobs"],
                "produces": ["application/json"],
                "parameters": [{
                    "in": "path",
                    "name": "id",
                    "description": "Job ID",
                    "required": true,
                    "type": "string"
                }],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.JobResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/metrics": {
            "get": {
                "summary": "Get cluster metrics",
                "description": "Returns metrics for a cluster, optionally filtered by type",
                "tags": ["Monitoring"],
                "produces": ["application/json"],
                "parameters": [{
                    "in": "query",
                    "name": "cluster_id",
                    "description": "Cluster ID to get metrics for",
                    "type": "string"
                }, {
                    "in": "query",
                    "name": "type",
                    "description": "Metric type (cpu, memory, disk, network)",
                    "type": "string"
                }],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GetMetricsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.HelloRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "models.HelloResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "models.Droplet": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "region": {
                    "type": "string"
                },
                "size": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string",
                    "format": "date-time"
                },
                "ip_address": {
                    "type": "string"
                }
            }
        },
        "models.CreateDropletRequest": {
            "type": "object",
            "required": ["name", "region", "size", "image"],
            "properties": {
                "name": {
                    "type": "string"
                },
                "region": {
                    "type": "string"
                },
                "size": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                }
            }
        },
        "models.DropletResponse": {
            "type": "object",
            "properties": {
                "droplet": {
                    "$ref": "#/definitions/models.Droplet"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.ListDropletsResponse": {
            "type": "object",
            "properties": {
                "droplets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Droplet"
                    }
                }
            }
        },
        "models.DeleteDropletResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "models.Cluster": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "region": {
                    "type": "string"
                },
                "droplets": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "string"
                },
                "last_checked": {
                    "type": "string",
                    "format": "date-time"
                }
            }
        },
        "models.DiagnoseClusterRequest": {
            "type": "object",
            "required": ["cluster_id"],
            "properties": {
                "cluster_id": {
                    "type": "string"
                }
            }
        },
        "models.DiagnoseClusterResponse": {
            "type": "object",
            "properties": {
                "cluster": {
                    "$ref": "#/definitions/models.Cluster"
                },
                "insights": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "recommendations": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.Job": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string",
                    "format": "date-time"
                },
                "completed_at": {
                    "type": "string",
                    "format": "date-time"
                },
                "result": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "models.CreateJobRequest": {
            "type": "object",
            "required": ["type"],
            "properties": {
                "type": {
                    "type": "string"
                },
                "parameters": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "models.JobResponse": {
            "type": "object",
            "properties": {
                "job": {
                    "$ref": "#/definitions/models.Job"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.ListJobsResponse": {
            "type": "object",
            "properties": {
                "jobs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Job"
                    }
                }
            }
        },
        "models.Metric": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "cluster_id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "value": {
                    "type": "number",
                    "format": "float"
                },
                "timestamp": {
                    "type": "string",
                    "format": "date-time"
                },
                "unit": {
                    "type": "string"
                }
            }
        },
        "models.GetMetricsResponse": {
            "type": "object",
            "properties": {
                "metrics": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Metric"
                    }
                },
                "period": {
                    "type": "string"
                }
            }
        }
    },
    "tags": [
        {
            "name": "Hello",
            "description": "Basic greeting endpoints"
        },
        {
            "name": "Provisioning",
            "description": "Droplet management and provisioning"
        },
        {
            "name": "Diagnosis",
            "description": "Cluster health diagnosis and analysis"
        },
        {
            "name": "Jobs",
            "description": "Job management and execution"
        },
        {
            "name": "Monitoring",
            "description": "Metrics and monitoring data"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "ClusterGenie API",
	Description:      "REST API for ClusterGenie - DigitalOcean droplet management and monitoring",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
